s=set()
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
n=input("enter no.::")
s.add(int(n))
print(s)
